import {useEffect,useMemo,useRef,useState} from 'react';

type Answer=string|number|boolean;
type VoiceSample={promptId:string;durationMs:number;rms:number;pauseRatio:number};
type Session={id:string;date:string;observation?:{quality:number;lighting:number};listening?:{confidence:number;samples:VoiceSample[]};inquiry?:{answers:{id:string;value:Answer}[]};tongue?:{quality:number;provider:string};report?:{confidence:number;summary:string;signals:string[];recommendations:string[]}};

const questions=[
 ['han-nhiet','Hôm nay bạn thấy cơ thể thiên về lạnh hay nóng hơn bình thường?','single'],['han','Bạn có ra mồ hôi bất thường khi nghỉ ngơi không?','yes-no'],['dau-than','Bạn có đau đầu, nặng đầu hoặc mỏi thân thể hôm nay không?','yes-no'],['nhi-tien','Đại tiện hoặc tiểu tiện hôm nay có khác thường không?','yes-no'],['am-thuc','Bạn có khát nhiều, khô miệng hoặc thay đổi khẩu vị rõ rệt không?','yes-no'],['hung-phuc','Bạn có cảm giác tức ngực, đầy bụng hoặc khó chịu vùng ngực-bụng không?','yes-no'],['thinh-giac','Bạn có ù tai, nghe kém hoặc cảm giác âm thanh khác thường hôm nay không?','yes-no'],['ngu','Chất lượng giấc ngủ đêm qua bạn tự đánh giá bao nhiêu?','scale'],['cam-xuc','Mức độ căng thẳng cảm nhận hôm nay là bao nhiêu?','scale'],['khac','Bạn có triệu chứng mới nào xuất hiện từ hôm qua đến nay không?','yes-no']
] as const;
const prompts=[
 'Sáng nay tôi cảm thấy hơi thở đều và giọng nói tự nhiên.','Tôi đọc chậm, rõ từng tiếng và giữ nhịp thở ổn định.','Âm thanh phát ra liên tục, không gắng sức và không nói quá nhanh.','Hôm nay cơ thể tôi đang ở trạng thái bình thường như mọi ngày.','Giọng nói tự nhiên của tôi được ghi lại để so sánh với chính mình theo thời gian.'
];
const today=()=>new Intl.DateTimeFormat('en-CA').format(new Date());
const clamp=(n:number)=>Math.max(0,Math.min(1,n));

async function openCamera(video:HTMLVideoElement){const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();return()=>stream.getTracks().forEach(t=>t.stop())}
function analyzeFrame(video:HTMLVideoElement){const c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d',{willReadFrequently:true});if(!x)throw new Error();x.drawImage(video,0,0,320,240);const d=x.getImageData(80,35,160,170).data;let s=0,s2=0,n=0,dark=0,bright=0;for(let i=0;i<d.length;i+=16){const l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255;s+=l;s2+=l*l;n++;if(l<.08)dark++;if(l>.96)bright++}const m=s/n,contrast=Math.sqrt(Math.max(0,s2/n-m*m));const lighting=clamp(1-Math.abs(m-.52)*1.7-(dark/n)*1.8-(bright/n)*1.8);return{quality:clamp(lighting*.75+clamp(contrast/.18)*.25),lighting}}
async function recordPrompt(promptId:string){const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false},video:false});const ac=new AudioContext(),src=ac.createMediaStreamSource(stream),an=ac.createAnalyser();an.fftSize=2048;src.connect(an);const arr=new Float32Array(an.fftSize);let sum=0,silent=0,frames=0;const start=performance.now();await new Promise<void>(resolve=>{const timer=setInterval(()=>{an.getFloatTimeDomainData(arr);let sq=0;for(const v of arr)sq+=v*v;const rms=Math.sqrt(sq/arr.length);sum+=rms;if(rms<.025)silent++;frames++;if(performance.now()-start>=4200){clearInterval(timer);resolve()}},80)});stream.getTracks().forEach(t=>t.stop());src.disconnect();await ac.close();return{promptId,durationMs:Math.round(performance.now()-start),rms:sum/Math.max(1,frames),pauseRatio:silent/Math.max(1,frames)}}

export default function App(){
 const date=useMemo(today,[]),videoRef=useRef<HTMLVideoElement|null>(null),stopRef=useRef<(()=>void)|null>(null);
 const [step,setStep]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[activeVoice,setActiveVoice]=useState<number|null>(null),[samples,setSamples]=useState<VoiceSample[]>([]),[answers,setAnswers]=useState<Record<string,Answer>>({}),[tongue,setTongue]=useState('');
 const [session,setSession]=useState<Session>({id:`local:${date}:${Date.now()}`,date});
 useEffect(()=>()=>stopRef.current?.(),[]);useEffect(()=>{if(step!==1){stopRef.current?.();stopRef.current=null}},[step]);
 const startCam=async()=>{if(!videoRef.current)return;setBusy(true);setMessage('');try{stopRef.current?.();stopRef.current=await openCamera(videoRef.current)}catch{setMessage('Không mở được camera. Hãy cấp quyền camera và thử lại.')}finally{setBusy(false)}};
 const scan=()=>{if(!videoRef.current)return;try{const observation=analyzeFrame(videoRef.current);setSession(s=>({...s,observation}));setStep(2)}catch{setMessage('Khung hình chưa sẵn sàng. Hãy thử lại.')}};
 const voice=async(i:number)=>{if(activeVoice!==null)return;setActiveVoice(i);setMessage('');try{const sample=await recordPrompt(`v-${i+1}`);setSamples(p=>[...p.filter(x=>x.promptId!==sample.promptId),sample])}catch{setMessage('Không ghi nhận được micro. Hãy cấp quyền micro và thử lại.')}finally{setActiveVoice(null)}};
 const finishVoice=()=>{if(samples.length!==5){setMessage('Cần hoàn tất đủ 5 câu đọc.');return}const confidence=Math.max(.45,1-samples.reduce((a,s)=>a+(s.pauseRatio>.65?.08:0),0));setSession(s=>({...s,listening:{confidence,samples}}));setMessage('');setStep(3)};
 const finishInquiry=()=>{if(questions.some(q=>answers[q[0]]===undefined)){setMessage('Cần trả lời đủ 10 câu hỏi.');return}setSession(s=>({...s,inquiry:{answers:questions.map(q=>({id:q[0],value:answers[q[0]]}))}}));setMessage('');setStep(4)};
 const chooseTongue=async(file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>setTongue(String(r.result));r.readAsDataURL(file)};
 const finishTongue=()=>{if(!tongue){setMessage('Cần chụp hoặc chọn một ảnh lưỡi.');return}setSession(s=>({...s,tongue:{quality:.7,provider:'tongue-adapter-ready'}}));setMessage('');setStep(5)};
 useEffect(()=>{if(step!==5||session.report)return;const signals:string[]=[];if(session.observation&&session.observation.quality<.65)signals.push('Vọng: chất lượng ảnh chưa tối ưu.');if(session.listening&&session.listening.confidence<.65)signals.push('Văn: dữ liệu giọng nói có độ tin cậy thấp.');const positives=session.inquiry?.answers.filter(a=>a.value===true||(typeof a.value==='number'&&a.value>=4))||[];positives.slice(0,4).forEach(a=>signals.push(`Vấn: tín hiệu cần theo dõi ở nhóm ${a.id}.`));const report={confidence:Math.max(.4,1-signals.length*.08),summary:signals.length?'Có một số thay đổi hoặc dữ liệu cần theo dõi trong phiên Tứ Chẩn hôm nay.':'Phiên Tứ Chẩn hôm nay chưa ghi nhận tín hiệu nổi bật từ dữ liệu V1.',signals,recommendations:['Duy trì điều kiện ghi nhận tương tự mỗi ngày.','Theo dõi thay đổi qua nhiều ngày thay vì dựa vào một phiên đơn lẻ.']};const done={...session,report};setSession(done);const old=JSON.parse(localStorage.getItem('tu-chan:v1:sessions')||'[]');localStorage.setItem('tu-chan:v1:sessions',JSON.stringify([done,...old.filter((x:Session)=>x.id!==done.id)].slice(0,100)))},[step,session]);
 const reset=()=>{setSession({id:`local:${date}:${Date.now()}`,date});setStep(0);setMessage('');setSamples([]);setAnswers({});setTongue('')};
 return <main className="shell"><section className="card hero"><div><span className="kicker">TỨ CHẨN YHCT AI · V1</span><h1>Theo dõi buổi sáng</h1><p>Vọng · Văn · Vấn · Thiệt trong một quy trình độc lập.</p></div><div className="date">{date}</div></section>{step>0&&<div className="progress"><i style={{width:`${Math.min(100,step*25)}%`}}/></div>}{message&&<div className="alert">{message}</div>}
 {step===0&&<section className="card start"><div className="orbit"><span>望</span><span>聞</span><span>問</span><span>舌</span></div><h2>Bắt đầu Tứ Chẩn sáng nay</h2><p>Dữ liệu camera và micro được xử lý tại thiết bị. Không tải media thô lên cloud mặc định.</p><button className="primary" onClick={()=>setStep(1)}>Bắt đầu</button></section>}
 {step===1&&<section className="card"><header className="stephead"><b>1/4</b><div><h2>Vọng</h2><p>Giữ mặt thẳng, đủ sáng, không ngược sáng.</p></div></header><div className="camera"><video ref={videoRef} muted playsInline/><div className="guide"/></div><div className="actions"><button className="btn" onClick={startCam} disabled={busy}>Mở camera</button><button className="primary" onClick={scan}>Quét khuôn mặt</button></div></section>}
 {step===2&&<section className="card"><header className="stephead"><b>2/4</b><div><h2>Văn</h2><p>Đọc tự nhiên 5 câu, mỗi câu khoảng 4 giây.</p></div></header><div className="list">{prompts.map((p,i)=>{const done=samples.some(s=>s.promptId===`v-${i+1}`);return <article className={`row ${done?'done':''}`} key={p}><span>{i+1}</span><p>{p}</p><button className="btn" onClick={()=>void voice(i)} disabled={activeVoice!==null}>{activeVoice===i?'Đang nghe…':done?'Đọc lại':'Đọc câu'}</button></article>})}</div><button className="primary wide" onClick={finishVoice}>Tiếp tục ({samples.length}/5)</button></section>}
 {step===3&&<section className="card"><header className="stephead"><b>3/4</b><div><h2>Vấn · Thập vấn</h2><p>10 nhóm câu hỏi chuẩn hóa cho theo dõi hằng ngày.</p></div></header><div className="questions">{questions.map((q,i)=><article key={q[0]}><b>{i+1}. {q[1]}</b>{q[2]==='yes-no'?<div className="choice"><button className={answers[q[0]]===false?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:false}))}>Không</button><button className={answers[q[0]]===true?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:true}))}>Có</button></div>:q[2]==='scale'?<div className="scale">{[1,2,3,4,5].map(n=><button key={n} className={answers[q[0]]===n?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:n}))}>{n}</button>)}</div>:<div className="choice"><button className={answers[q[0]]==='low'?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:'low'}))}>Thấp/lạnh hơn</button><button className={answers[q[0]]==='normal'?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:'normal'}))}>Bình thường</button><button className={answers[q[0]]==='high'?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:'high'}))}>Cao/nóng hơn</button></div>}</article>)}</div><button className="primary wide" onClick={finishInquiry}>Tiếp tục</button></section>}
 {step===4&&<section className="card"><header className="stephead"><b>4/4</b><div><h2>Thiệt chẩn</h2><p>Chụp lưỡi rõ nét, ánh sáng trắng, không dùng filter.</p></div></header><label className="upload">{tongue?<img src={tongue} alt="Ảnh lưỡi đã chọn"/>:<span>Chạm để chụp/chọn ảnh lưỡi</span>}<input type="file" accept="image/*" capture="environment" onChange={e=>void chooseTongue(e.target.files?.[0])}/></label><p className="note">Adapter Thiệt chẩn đã tách độc lập. Engine phân tích lưỡi thật sẽ nối tại adapter này; V1 không giả lập chẩn đoán lưỡi.</p><button className="primary wide" onClick={finishTongue}>Hoàn tất Thiệt chẩn</button></section>}
 {step===5&&<section className="card"><header className="stephead"><b>✓</b><div><h2>Tổng hợp hôm nay</h2><p>Báo cáo hỗ trợ theo dõi, không thay thế chẩn đoán y tế.</p></div></header>{session.report&&<><div className="score"><strong>{Math.round(session.report.confidence*100)}</strong><span>% độ tin cậy dữ liệu V1</span></div><h3>{session.report.summary}</h3>{session.report.signals.length>0&&<ul>{session.report.signals.map(x=><li key={x}>{x}</li>)}</ul>}<p className="note">Diễn giải chỉ mang tính hỗ trợ theo nguyên lý Y học cổ truyền; không đồng nhất với chẩn đoán y học hiện đại.</p><div className="recs">{session.report.recommendations.map(x=><span key={x}>{x}</span>)}</div><button className="primary wide" onClick={reset}>Kết thúc phiên</button></>}</section>}
 </main>;
}