import {useEffect,useMemo,useRef,useState} from 'react';
import {neonClient,neonConfigured} from './neonClient';
import {emptyBaseline,fuseSession,updateBaseline} from './healthEngine';
import {cachedSessions,ensureProfile,loadBaseline,loadRecentSessions,saveBaseline,saveSession,syncPending} from './healthStore';
import type {Answer,BaselineRecord,HealthSession,SafetyAnswer,VoiceSample} from './healthTypes';

const questions=[['han-nhiet','Hôm nay bạn thấy cơ thể thiên về lạnh hay nóng hơn bình thường?','single'],['han','Bạn có ra mồ hôi bất thường khi nghỉ ngơi không?','yes-no'],['dau-than','Bạn có đau đầu, nặng đầu hoặc mỏi thân thể hôm nay không?','yes-no'],['nhi-tien','Đại tiện hoặc tiểu tiện hôm nay có khác thường không?','yes-no'],['am-thuc','Bạn có khát nhiều, khô miệng hoặc thay đổi khẩu vị rõ rệt không?','yes-no'],['hung-phuc','Bạn có cảm giác tức ngực, đầy bụng hoặc khó chịu vùng ngực-bụng không?','yes-no'],['thinh-giac','Bạn có ù tai, nghe kém hoặc cảm giác âm thanh khác thường hôm nay không?','yes-no'],['ngu','Chất lượng giấc ngủ đêm qua bạn tự đánh giá bao nhiêu?','scale'],['cam-xuc','Mức độ căng thẳng cảm nhận hôm nay là bao nhiêu?','scale'],['khac','Bạn có triệu chứng mới nào xuất hiện từ hôm qua đến nay không?','yes-no']] as const;
const safetyQuestions=[['severe-chest-pain','Đau ngực dữ dội hoặc cảm giác đè nặng ngực đang xảy ra?'],['severe-dyspnea','Khó thở nhiều, tím tái hoặc không thể nói trọn câu?'],['syncope','Ngất, lơ mơ hoặc mất ý thức gần đây?'],['focal-neuro','Yếu/liệt đột ngột một bên, méo miệng hoặc nói khó mới xuất hiện?']] as const;
const prompts=['Sáng nay tôi cảm thấy hơi thở đều và giọng nói tự nhiên.','Tôi đọc chậm, rõ từng tiếng và giữ nhịp thở ổn định.','Âm thanh phát ra liên tục, không gắng sức và không nói quá nhanh.','Hôm nay cơ thể tôi đang ở trạng thái bình thường như mọi ngày.','Giọng nói tự nhiên của tôi được ghi lại để so sánh với chính mình theo thời gian.'];
const today=()=>new Intl.DateTimeFormat('en-CA').format(new Date());
const clamp=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,n));
const newSession=():HealthSession=>({id:crypto.randomUUID(),date:today(),capturedAt:new Date().toISOString(),syncState:'local'});

async function openCamera(video:HTMLVideoElement){const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();return()=>stream.getTracks().forEach(t=>t.stop())}
function analyzeFrame(video:HTMLVideoElement){const c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d',{willReadFrequently:true});if(!x)throw new Error();x.drawImage(video,0,0,320,240);const d=x.getImageData(80,35,160,170).data;let s=0,s2=0,n=0,dark=0,bright=0;for(let i=0;i<d.length;i+=16){const l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255;s+=l;s2+=l*l;n++;if(l<.08)dark++;if(l>.96)bright++}const m=s/n,contrast=Math.sqrt(Math.max(0,s2/n-m*m));const lighting=clamp(1-Math.abs(m-.52)*1.7-(dark/n)*1.8-(bright/n)*1.8);return{quality:clamp(lighting*.75+clamp(contrast/.18)*.25),lighting}}
async function recordPrompt(promptId:string){const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false},video:false});const ac=new AudioContext(),src=ac.createMediaStreamSource(stream),an=ac.createAnalyser();an.fftSize=2048;src.connect(an);const arr=new Float32Array(an.fftSize);let sum=0,silent=0,frames=0;const start=performance.now();await new Promise<void>(resolve=>{const timer=setInterval(()=>{an.getFloatTimeDomainData(arr);let sq=0;for(const v of arr)sq+=v*v;const rms=Math.sqrt(sq/arr.length);sum+=rms;if(rms<.025)silent++;frames++;if(performance.now()-start>=4200){clearInterval(timer);resolve()}},80)});stream.getTracks().forEach(t=>t.stop());src.disconnect();await ac.close();return{promptId,durationMs:Math.round(performance.now()-start),rms:sum/Math.max(1,frames),pauseRatio:silent/Math.max(1,frames)}}
async function readTongue(file:File){const dataUrl=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=dataUrl});const c=document.createElement('canvas');c.width=160;c.height=160;const x=c.getContext('2d',{willReadFrequently:true});if(!x)return{dataUrl,quality:.5};x.drawImage(img,0,0,160,160);const d=x.getImageData(0,0,160,160).data;let s=0,s2=0,n=0;for(let i=0;i<d.length;i+=16){const l=(d[i]+d[i+1]+d[i+2])/(255*3);s+=l;s2+=l*l;n++}const mean=s/n,contrast=Math.sqrt(Math.max(0,s2/n-mean*mean));return{dataUrl,quality:clamp(.55+contrast*1.8-Math.abs(mean-.55)*.7,.25,1)}}

function AuthScreen({client}:{client:any}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[mode,setMode]=useState<'in'|'up'>('in'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setMessage('');try{const result=mode==='in'?await client.auth.signIn.email({email,password}):await client.auth.signUp.email({email,password,name:name||email.split('@')[0]});if(result?.error)throw result.error;location.reload()}catch(e:any){setMessage(e?.message||'Không thể xác thực. Vui lòng kiểm tra thông tin.')}finally{setBusy(false)}};return <main className="shell"><section className="card hero"><div><span className="kicker">TỨ CHẨN YHCT AI · V2</span><h1>Health Timeline</h1><p>Dữ liệu sức khỏe cá nhân được tách theo tài khoản bằng Neon RLS.</p></div></section><section className="card auth"><h2>{mode==='in'?'Đăng nhập':'Tạo tài khoản'}</h2>{mode==='up'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên hiển thị"/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu" type="password"/>{message&&<div className="alert">{message}</div>}<button className="primary wide" onClick={()=>void submit()} disabled={busy}>{busy?'Đang xử lý…':mode==='in'?'Đăng nhập':'Đăng ký'}</button><button className="linkbtn" onClick={()=>setMode(mode==='in'?'up':'in')}>{mode==='in'?'Chưa có tài khoản? Đăng ký':'Đã có tài khoản? Đăng nhập'}</button></section></main>}

function HealthApp({client,user}:{client:any,user:any}){const date=useMemo(today,[]),videoRef=useRef<HTMLVideoElement|null>(null),stopRef=useRef<(()=>void)|null>(null);const [step,setStep]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[activeVoice,setActiveVoice]=useState<number|null>(null),[samples,setSamples]=useState<VoiceSample[]>([]),[answers,setAnswers]=useState<Record<string,Answer>>({}),[safetyAnswers,setSafetyAnswers]=useState<Record<string,boolean>>({}),[tongue,setTongue]=useState(''),[tongueQuality,setTongueQuality]=useState(0),[session,setSession]=useState<HealthSession>(newSession),[baseline,setBaseline]=useState<BaselineRecord>(),[history,setHistory]=useState<HealthSession[]>(cachedSessions()),[syncLabel,setSyncLabel]=useState('Đang kết nối Neon…');
 useEffect(()=>()=>stopRef.current?.(),[]);useEffect(()=>{if(step!==1){stopRef.current?.();stopRef.current=null}},[step]);
 useEffect(()=>{let live=true;(async()=>{try{await ensureProfile(client,user.id,user.name);const synced=await syncPending(client,user.id);const [b,h]=await Promise.all([loadBaseline(client,user.id),loadRecentSessions(client,user.id)]);if(live){setBaseline(b);setHistory(h);setSyncLabel(synced?`Đã đồng bộ ${synced} phiên chờ`:'Neon · đã đồng bộ')}}catch{if(live)setSyncLabel('Offline-safe · sẽ tự đồng bộ')}})();return()=>{live=false}},[client,user.id,user.name]);
 const startCam=async()=>{if(!videoRef.current)return;setBusy(true);setMessage('');try{stopRef.current?.();stopRef.current=await openCamera(videoRef.current)}catch{setMessage('Không mở được camera. Hãy cấp quyền camera và thử lại.')}finally{setBusy(false)}};
 const scan=()=>{if(!videoRef.current)return;try{setSession(s=>({...s,observation:analyzeFrame(videoRef.current)}));setStep(2)}catch{setMessage('Khung hình chưa sẵn sàng. Hãy thử lại.')}};
 const voice=async(i:number)=>{if(activeVoice!==null)return;setActiveVoice(i);setMessage('');try{const sample=await recordPrompt(`v-${i+1}`);setSamples(p=>[...p.filter(x=>x.promptId!==sample.promptId),sample])}catch{setMessage('Không ghi nhận được micro. Hãy cấp quyền micro và thử lại.')}finally{setActiveVoice(null)}};
 const finishVoice=()=>{if(samples.length!==5){setMessage('Cần hoàn tất đủ 5 câu đọc.');return}const confidence=Math.max(.45,1-samples.reduce((a,s)=>a+(s.pauseRatio>.65?.08:0),0));setSession(s=>({...s,listening:{confidence,samples}}));setMessage('');setStep(3)};
 const finishInquiry=()=>{if(questions.some(q=>answers[q[0]]===undefined)){setMessage('Cần trả lời đủ 10 câu hỏi.');return}setSession(s=>({...s,inquiry:{answers:questions.map(q=>({id:q[0],value:answers[q[0]]}))}}));setMessage('');setStep(4)};
 const chooseTongue=async(file?:File)=>{if(!file)return;try{const r=await readTongue(file);setTongue(r.dataUrl);setTongueQuality(r.quality)}catch{setMessage('Không đọc được ảnh lưỡi. Hãy thử ảnh khác.')}};
 const finishTongue=()=>{if(!tongue){setMessage('Cần chụp hoặc chọn một ảnh lưỡi.');return}setSession(s=>({...s,tongue:{quality:tongueQuality,provider:'local-quality-adapter-v2'}}));setMessage('');setStep(5)};
 const finishSafety=async()=>{if(safetyQuestions.some(q=>safetyAnswers[q[0]]===undefined)){setMessage('Cần hoàn tất sàng lọc an toàn.');return}setBusy(true);setMessage('');const safetyList=safetyQuestions.map(q=>({id:q[0],value:safetyAnswers[q[0]]})) as SafetyAnswer[];const prepared={...session,userId:user.id,safetyAnswers:safetyList,capturedAt:new Date().toISOString()};const fused=fuseSession(prepared,baseline);const done:HealthSession={...prepared,...fused};setSession(done);setStep(6);const saved=await saveSession(client,user.id,done);const next=updateBaseline(baseline||emptyBaseline(user.id),fused.featureVector,done.capturedAt);next.userId=user.id;try{await saveBaseline(client,next);setBaseline(next)}catch{}setHistory(await loadRecentSessions(client,user.id));setSyncLabel(saved.synced?'Neon · đã lưu':'Offline-safe · phiên đang chờ đồng bộ');setBusy(false)};
 const reset=()=>{setSession(newSession());setStep(0);setMessage('');setSamples([]);setAnswers({});setSafetyAnswers({});setTongue('');setTongueQuality(0)};
 const signOut=async()=>{await client.auth.signOut();location.reload()};
 return <main className="shell"><section className="card hero"><div><span className="kicker">TỨ CHẨN YHCT AI · CONTINUOUS</span><h1>Theo dõi sức khỏe cá nhân</h1><p>Vọng · Văn · Vấn · Thiệt · Safety · Baseline</p></div><div className="date">{date}</div></section><div className="accountbar"><span>{user.name||user.email}</span><span>{syncLabel}</span><button onClick={()=>void signOut()}>Đăng xuất</button></div>{step>0&&<div className="progress"><i style={{width:`${Math.min(100,step*20)}%`}}/></div>}{message&&<div className="alert">{message}</div>}
 {step===0&&<><section className="card dashboard"><div><span className="kicker dark">BASELINE CÁ NHÂN</span><h2>{baseline?.sessionCount||0} phiên đã học</h2><p>Hệ thống cập nhật trung bình và độ biến thiên của chính bạn sau mỗi phiên; không tự thay đổi model chẩn đoán nền.</p></div><button className="primary" onClick={()=>setStep(1)}>Bắt đầu Tứ Chẩn hôm nay</button></section><section className="card"><h2>Xu hướng gần đây</h2>{history.length===0?<p className="muted">Chưa có dữ liệu lịch sử.</p>:<div className="timeline">{history.slice(0,7).map(h=><article key={h.id}><b>{h.date}</b><span>Nguy cơ {Math.round((h.fusion?.riskScore||0)*100)}%</span><span>Xu hướng {Math.round((h.fusion?.trendScore||0)*100)}%</span><em className={h.safety?.severity||'info'}>{h.safety?.severity==='urgent'?'Cần đánh giá khẩn':h.safety?.severity==='watch'?'Theo dõi':'Ổn định'}</em></article>)}</div>}</section></>}
 {step===1&&<section className="card"><header className="stephead"><b>1/5</b><div><h2>Vọng</h2><p>Giữ mặt thẳng, đủ sáng, không ngược sáng.</p></div></header><div className="camera"><video ref={videoRef} muted playsInline/><div className="guide"/></div><div className="actions"><button className="btn" onClick={startCam} disabled={busy}>Mở camera</button><button className="primary" onClick={scan}>Quét chất lượng</button></div><p className="note">Chỉ lưu đặc trưng chất lượng; không tải video/ảnh mặt thô lên cloud.</p></section>}
 {step===2&&<section className="card"><header className="stephead"><b>2/5</b><div><h2>Văn</h2><p>Đọc tự nhiên 5 câu, mỗi câu khoảng 4 giây.</p></div></header><div className="list">{prompts.map((p,i)=>{const done=samples.some(s=>s.promptId===`v-${i+1}`);return <article className={`row ${done?'done':''}`} key={p}><span>{i+1}</span><p>{p}</p><button className="btn" onClick={()=>void voice(i)} disabled={activeVoice!==null}>{activeVoice===i?'Đang nghe…':done?'Đọc lại':'Đọc câu'}</button></article>})}</div><button className="primary wide" onClick={finishVoice}>Tiếp tục ({samples.length}/5)</button></section>}
 {step===3&&<section className="card"><header className="stephead"><b>3/5</b><div><h2>Vấn · Thập vấn</h2><p>10 nhóm câu hỏi được đưa vào baseline theo thời gian.</p></div></header><div className="questions">{questions.map((q,i)=><article key={q[0]}><b>{i+1}. {q[1]}</b>{q[2]==='yes-no'?<div className="choice"><button className={answers[q[0]]===false?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:false}))}>Không</button><button className={answers[q[0]]===true?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:true}))}>Có</button></div>:q[2]==='scale'?<div className="scale">{[1,2,3,4,5].map(n=><button key={n} className={answers[q[0]]===n?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:n}))}>{n}</button>)}</div>:<div className="choice"><button className={answers[q[0]]==='low'?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:'low'}))}>Thấp/lạnh hơn</button><button className={answers[q[0]]==='normal'?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:'normal'}))}>Bình thường</button><button className={answers[q[0]]==='high'?'selected':''} onClick={()=>setAnswers(a=>({...a,[q[0]]:'high'}))}>Cao/nóng hơn</button></div>}</article>)}</div><button className="primary wide" onClick={finishInquiry}>Tiếp tục</button></section>}
 {step===4&&<section className="card"><header className="stephead"><b>4/5</b><div><h2>Thiệt chẩn</h2><p>Chụp lưỡi rõ nét, ánh sáng trắng, không dùng filter.</p></div></header><label className="upload">{tongue?<img src={tongue} alt="Ảnh lưỡi đã chọn"/>:<span>Chạm để chụp/chọn ảnh lưỡi</span>}<input type="file" accept="image/*" capture="environment" onChange={e=>void chooseTongue(e.target.files?.[0])}/></label><p className="note">V2 chỉ đánh giá chất lượng ảnh và giữ adapter cho engine lưỡi chuyên biệt; ảnh thô không được lưu lên Neon.</p><button className="primary wide" onClick={finishTongue}>Tiếp tục</button></section>}
 {step===5&&<section className="card"><header className="stephead"><b>5/5</b><div><h2>Safety layer</h2><p>Sàng lọc cờ đỏ trước khi đưa lời khuyên.</p></div></header><div className="questions safety">{safetyQuestions.map((q,i)=><article key={q[0]}><b>{i+1}. {q[1]}</b><div className="choice"><button className={safetyAnswers[q[0]]===false?'selected':''} onClick={()=>setSafetyAnswers(a=>({...a,[q[0]]:false}))}>Không</button><button className={safetyAnswers[q[0]]===true?'dangerSelected':''} onClick={()=>setSafetyAnswers(a=>({...a,[q[0]]:true}))}>Có</button></div></article>)}</div><button className="primary wide" onClick={()=>void finishSafety()} disabled={busy}>{busy?'Đang tổng hợp…':'Tổng hợp AI'}</button></section>}
 {step===6&&session.fusion&&session.safety&&session.recommendation&&<section className="card"><header className="stephead"><b>✓</b><div><h2>Tổng hợp hôm nay</h2><p>AI fusion so với baseline cá nhân, không thay thế chẩn đoán trực tiếp.</p></div></header><div className="scoregrid"><div className="score"><strong>{Math.round(session.fusion.confidence*100)}</strong><span>% tin cậy dữ liệu</span></div><div className="score"><strong>{Math.round(session.fusion.riskScore*100)}</strong><span>% mức cần theo dõi</span></div></div><div className={`safetybox ${session.safety.severity}`}><b>{session.safety.severity==='urgent'?'CỜ ĐỎ':session.safety.severity==='watch'?'CẦN THEO DÕI':'CHƯA CÓ CỜ ĐỎ'}</b><p>{session.safety.message}</p></div><h3>{session.fusion.summary}</h3>{session.fusion.signals.length>0&&<ul>{session.fusion.signals.map(x=><li key={x}>{x}</li>)}</ul>}<div className="recs">{session.recommendation.items.map(x=><span key={x}>{x}</span>)}{session.recommendation.diagnosticDirection.map(x=><span key={x}><b>Định hướng:</b> {x}</span>)}</div><p className="note">Không xuất bệnh danh chắc chắn. Nếu có cờ đỏ, ưu tiên đánh giá y tế trực tiếp/cấp cứu trước mọi diễn giải YHCT.</p><button className="primary wide" onClick={reset}>Kết thúc phiên</button></section>}
 </main>}

function CloudRoot({client}:{client:any}){const session=client.auth.useSession();if(session.isPending)return <main className="shell"><section className="card"><p>Đang xác thực Neon…</p></section></main>;if(!session.data?.user)return <AuthScreen client={client}/>;return <HealthApp client={client} user={session.data.user}/>}
export default function App(){if(!neonConfigured||!neonClient)return <main className="shell"><section className="card hero"><div><span className="kicker">TỨ CHẨN YHCT AI</span><h1>Backend chưa cấu hình</h1><p>Thiếu VITE_NEON_AUTH_URL hoặc VITE_NEON_DATA_API_URL.</p></div></section></main>;return <CloudRoot client={neonClient}/>}
